### ISSUE TITLE
Minecraft Crashes right before world loads

### ISSUE THREAD

**Issue by furtabs** [Arc-blroth/ProjectInception#4]
**Link to Log** (must be a link to a pastebin-like site. Logs can be found in the logs folder under your minecraft or modpack folder)
https://gist.github.com/CrankySupertoon/f7fd95ce4031368d7673fbb5b843a9a9

**Bug Description**
Load the game. Right before it shows main menu. Crashes

**Environment**
OS: Arch
Minecraft version 1.16.2
Fabric Loader version 0.10.0+build.208

**What were you doing that may have led up to or caused the issue?**
maybe loading the game isnt how to actual use the mod

**Comment by Arc-blroth** [comment]
Sorry I haven't been able to look at this issue quickly (was busy with issue 2), but it seems like the culprit is mismatched versions of one of the mod's dependencies (slf4j). Project Inception includes and expects version 2.0 of that dependency, but it seems like that another mod is including version 1.8, if the modlist is correct.
I'll see if I can figure out which mod is responsible, and see if I can write some sort of compatibility around this.

**Comment by Arc-blroth** [comment]
It turns out the culprit is Gunpowder
https://github.com/Gunpowder-MC/Gunpowder/blob/master/gunpowder-base/build.gradle#L27
I will figure out a fix soon™
